# NumPy

Read the links: https://numpy.org/doc/stable/user/quickstart.html  and https://numpy.org/doc/stable/user/basics.broadcasting.html  before solving the exercises. 

In [43]:
import numpy as np

### Print out the dimension (number of axes), shape, size and the datatype of the matrix A.

In [44]:
A = np.arange(1, 16).reshape(3,5)

In [45]:
# Print number of axes
print(A.ndim) 

# Print shape
print(A.shape)

# Print number of elements
print(A.size)

# Print datatype
print(A.dtype)

2
(3, 5)
15
int32


### Do the following computations on the matrices B and C: 
* Elementwise subtraction. 
* Elementwise multiplication. 
* Matrix multiplication (by default you should use the @ operator).

In [46]:
B = np.arange(1, 10).reshape(3, 3)
C = np.ones((3, 3))*2

print(B)
print()
print(C)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]


In [5]:
# Elementwise subtraction
print(B-C)
print()

# Elementwise multiplication
print(B*C)
print()

# Matrix multiplication
print(B@C)

[[-1.  0.  1.]
 [ 2.  3.  4.]
 [ 5.  6.  7.]]

[[ 2.  4.  6.]
 [ 8. 10. 12.]
 [14. 16. 18.]]

[[12. 12. 12.]
 [30. 30. 30.]
 [48. 48. 48.]]


### Do the following calculations on the matrix:
* Exponentiate each number elementwise (use the np.exp function).

* Calculate the minimum value in the whole matrix. 
* Calculcate the minimum value in each row. 
* Calculcate the minimum value in each column. 


* Find the index value for the minimum value in the whole matrix (hint: use np.argmin).
* Find the index value for the minimum value in each row (hint: use np.argmin).


* Calculate the sum for all elements.
* Calculate the mean for each column. 
* Calculate the median for each column. 

In [54]:
B = np.arange(1, 10).reshape(3, 3)

print(B)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [55]:
# Exponentiate each number elementwise
print(np.exp(B))

# Calculate the minimum value in the matrix
min_value = B.min()
print(min_value)

# Calculate the maximum value in the matrix
max_value = B.max()
print(max_value)

# Calculcate the minimum value in each row
print(B.min(axis=0))

# Calculcate the minimum value in each column
print(B.min(axis=1))

# Find the index value for the minimum value in the whole matrix
print(np.argmin(B))

# Find the index value for the minimum value in each row
print(np.argmin(B, axis=1))

# Calculate the sum for all elements
sum_B = sum(B)
print(sum(sum_B))

# Calculate the mean for each column
sum_B = sum(sum_B) / 9
print(sum_B)

# Calculate the median for each column
print(sum(B) / 3)
print(np.mean(B))
print(np.median(B,axis=0))


[[2.71828183e+00 7.38905610e+00 2.00855369e+01]
 [5.45981500e+01 1.48413159e+02 4.03428793e+02]
 [1.09663316e+03 2.98095799e+03 8.10308393e+03]]
1
9
[1 2 3]
[1 4 7]
0
[0 0 0]
45
5.0
[4. 5. 6.]
5.0
[4. 5. 6.]


### What does it mean when you provide fewer indices than axes when slicing? See example below.

In [56]:
print(A)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [57]:
A[1]

array([ 6,  7,  8,  9, 10])

**Answer:**

In [11]:
# You only slice the "selected" row

### Iterating over multidimensional arrays is done with respect to the first axis, so in the example below we iterate trough the rows. If you would like to iterate through the array *elementwise*, how would you do that?

In [42]:
A

array([[ 3, -7, -2],
       [-3,  5,  1],
       [ 6, -4,  0]])

In [13]:
for i in A:
    print(i)

[1 2 3 4 5]
[ 6  7  8  9 10]
[11 12 13 14 15]


In [14]:
for i in A.flatten():
    print(i)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15


### Explain what the code below does. More specifically, b has three axes - what does this mean? 

In [15]:
# Create a 1D array that has 30 elements (0-29)
a = np.arange(30) 

# Create a 3D array with 2 as the first dimension, 3 as the second dimention and 
# "-1" makes sure that the third dimention fits with the number of elements.
b = a.reshape((2, 3, -1))

print(a)
print()
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]


### Broadcasting
**Read the following link about broadcasting: https://numpy.org/doc/stable/user/basics.broadcasting.html#basics-broadcasting**

# Remark on Broadcasting when doing Linear Algebra calculations in Python. 

### From the mathematical rules of matrix addition, the operation below (m1 + m2) does not make sense. The reason is that matrix addition requires two matrices of the same size. In Python however, it works due to broadcasting rules in NumPy. So you must be careful when doing Linear Algebra calculations in Python since they do not follow the "mathematical rules". This can however easily be handled by doing some simple programming, for example validating that two matrices have the same shape is easy if you for instance want to add two matrices. 

In [16]:
m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([1, 1])

# Check if m1 & m2 is the same shape.
# If they are, add them together and print it out, otherwise, print an "error" message
if m1.shape == m2.shape:
    print(m1 + m2)
else:
    print('Cannot add two matricies with different dimentions')

Cannot add two matricies with different dimentions


### The example below would also not be allowed if following the "mathematical rules" in Linear Algebra. But it works due to broadcasting in NumPy. 

In [17]:
v1 = np.array([1, 2, 3])
print(v1 + 1)

[2 3 4]


In [18]:
A = np.arange(1, 5).reshape(2,2)
print(A)

b = np.array([2, 2])
print(b)

[[1 2]
 [3 4]]
[2 2]


# Linear Algebra Exercises

The exercies are taken from the "Matrix Algebra for Engineers" by Chasnov: https://www.math.hkust.edu.hk/~machas/matrix-algebra-for-engineers.pdf .

Do the following exercises: 
* Chapter 2, exercise 1-3.
* Quiz on p.11, exercise 2. 
* Chapter 6, exercise 1. 
* Quiz on p.19, exercise 3. 


* Chapter 10, exercise 1. 
* Chapter 12 exercise 1. 


In [58]:
A = np.array([[2, 1, -1], [1, -1, 1]])
B = np.array([[4, -2, 1], [2, -4, -2]])

C = np.array([[1, 2], [2, 1]])
D = np.array([[3, 4], [4, 3]])

E = np.array([[1], [2]])

print(A)
print(B)
print(C)
print(D)
print(E)

[[ 2  1 -1]
 [ 1 -1  1]]
[[ 4 -2  1]
 [ 2 -4 -2]]
[[1 2]
 [2 1]]
[[3 4]
 [4 3]]
[[1]
 [2]]


**Chap2. Question 1.**

**Write a function "add_mult_matrices" that takes two matrices as input arguments (validate that the input are of the type numpy.ndarray by using the isinstance function), a third argument that is either 'add' or 'multiply' that specifies if you want to add or multiply the matrices (validate that the third argument is either 'add' or 'multiply'). When doing matrix addition, validate that the matrices have the same size. When doing matrix multiplication, validate that the sizes conform (i.e. number of columns in the first matrix is equal to the number of rows in the second matrix).**

In this exercise, create a function that takes two matrices as input and either adds or multiplies them by specifying a argument as either 'add' or 'multiply'. Validate that both matrices taken as input are of the type ndarray (use the isinstance function).

In [59]:
# Create a function that asks if you want to add or multiply your matrices and if you're not allowed to add/multiply those
# dimentions of matrices, print an "error message" 
def add_mult_matrices(matrix_1, matrix_2):

    #Check if the input is the type np.ndarray.
    if isinstance(matrix_1, np.ndarray) and isinstance(matrix_2, np.ndarray):
        user_input = input ('If you want to add the matrices, please type "add" or if you want to multiply the matrices, please type "multiply"')

        #Add the two matrices and check if they're the right dimentions
        if user_input == "add":
            if matrix_1.shape == matrix_2.shape:
                print(matrix_1 + matrix_2)
            else:
                print("You dummy, the matrices aren't the same size")

        #Multiply the two matrices and check if they're the right dimentions
        elif user_input == "multiply":
            if matrix_1.shape[1] == matrix_2.shape[0]:
                print(matrix_1 @ matrix_2)
            else:
                print('You dummy, you cannot multiply those two matrices')
        else:
            print('You dummy, I told you to write "add" or "multiply"! =(')
        
    else:
        print('You dummy, atleast one matrix is not a "np.ndarray"')

add_mult_matrices(B, -2*A)
print()
add_mult_matrices(3*C, -E)
print()
add_mult_matrices(A, C)
print()
add_mult_matrices(C, D)
print()
add_mult_matrices(C, B)

**Chap2. Question 2**

In [61]:
A = np.array([[1, 2], [2, 4]])
B = np.array([[2, 1], [1, 3]])
C = np.array([[4, 3], [0, 2]])

AB = add_mult_matrices(A, B)
AC = add_mult_matrices(A, C)


if AB == AC:
    print ("They are the same size!")
else:
    print("They aren't the same size!")

If you want to add the matrices, please type "add" or if you want to multiply the matrices, please type "multiply"add
[[3 3]
 [3 7]]
If you want to add the matrices, please type "add" or if you want to multiply the matrices, please type "multiply"multipply
You dummy, I told you to write "add" or "multiply"! =(
They are the same size!


**Chap2. Question 3**

In [62]:
A = np.array([[1, 1, 1], [1, 2, 3], [1, 3, 4]])
D = np.array([[2, 0, 0], [0, 3, 0], [0, 0, 4]])

AD = add_mult_matrices(A, D)
DA = add_mult_matrices(D, A)

If you want to add the matrices, please type "add" or if you want to multiply the matrices, please type "multiply"multiply
[[ 2  3  4]
 [ 2  6 12]
 [ 2  9 16]]
If you want to add the matrices, please type "add" or if you want to multiply the matrices, please type "multiply"multiply
[[ 2  2  2]
 [ 3  6  9]
 [ 4 12 16]]


**Quiz p.11, Question 2**

In [63]:
A = np.array([[1, -1], [-1, 1]])
B = np.array([[-1, 1], [1, -1]])

add_mult_matrices(A, B)

# Svar: a)

If you want to add the matrices, please type "add" or if you want to multiply the matrices, please type "multiply"multiply
[[-2  2]
 [ 2 -2]]


**Chap 6. Question 1**

In [64]:
A = np.array([[5, 6], [4, 5]])
B = np.array([[6, 4], [3, 3]])

A_inv = np.linalg.inv(A)
B_inv = np.linalg.inv(B)

print(A_inv)
print()
print(B_inv)

[[ 5. -6.]
 [-4.  5.]]

[[ 0.5        -0.66666667]
 [-0.5         1.        ]]


**Quiz p.19, Question 3**

In [26]:
matrix_A = np.array([[2, 2], [1, 2]])
inv_matrix = np.linalg.inv(matrix_A)

print(inv_matrix)

# Svar: a)

[[ 1.  -1. ]
 [-0.5  1. ]]


**Chap10. Question 1 a)**

In [27]:
A = np.array([[3, -7, -2], [3, 5, 1], [6, -4, 0]])
B = np.array([-7, 5, 2])

X = np.linalg.solve(A, B)

print('X1 =',int(X[0]))
print('X2 =',int(X[1]))
print('X3 =',int(X[2]))

X1 = 0
X2 = 0
X3 = 4


**Chap10. Question 1 b)**

In [28]:
A = np.array([[1, -2, 3], [-1, 3, -1], [2, -5, 5]])
B = np.array([1, -1, 1])

gauss_elimination = np.linalg.solve(A, B)

print('X1 =',int(gauss_elimination[0]))
print('X2 =',int(gauss_elimination[1]))
print('X3 =',int(gauss_elimination[2]))

X1 = 8
X2 = 2
X3 = -1


**Chap 12. Question 1**

In [29]:
A = np.array([[3, -7, -2], [-3, 5, 1], [6, -4, 0]])

inverse_A = np.linalg.inv(A)

print(inverse_A)

[[ 0.66666667  1.33333333  0.5       ]
 [ 1.          2.          0.5       ]
 [-3.         -5.         -1.        ]]


### Copies and Views
Read the following link: https://numpy.org/doc/stable/user/basics.copies.html

**Basic indexing creates a view, How can you check if v1 and v2 is a view or copy? If you change the last element in v2 to 123, will the last element in v1 be changed? Why?**

In [30]:
v1 = np.arange(4)
v2 = v1[-2:]
print(v1)
print(v2)

[0 1 2 3]
[2 3]


In [31]:
# The base attribute of a view returns the original array while it returns None for a copy.
print(v1.base)
print(v2.base)

None
[0 1 2 3]


In [32]:
# The last element in v1 will be changed aswell since v2 is a view, meaning they share the same data buffer.
v2[-1] = 123
print(v1)
print(v2)

[  0   1   2 123]
[  2 123]
